trade:
  target: 2
  start: "0:17"
  stop: "23:50"
  live: 1      # 0 for paper 1 for live
  strategy: openingbalance   #openingbalance/renko
log:
  show: 0
  level: 10
NIFTY:
  base: NIFTY
  option_exchange: NFO
  moneyness: -1       # 0=atm 1=otm -1=itm
  expiry: 05JUN25
  quantity: 75
  t1: 5
  t2: 2
  txn: 1             # points for each losing trade
  rest_min: 1
  brick_size: 10
